name: habit_tracker_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  dartz: ^0.10.1
  equatable: ^2.0.7
  internet_connection_checker: ^3.0.1
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.1
  cloud_firestore: ^6.0.0
  google_sign_in: ^7.1.1
  firebase_ai: ^3.1.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  get_it: ^8.2.0
  intl: ^0.20.2
  
  permission_handler: ^11.3.1
  firebase_storage: ^13.0.0
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true


assets:
  - assets/images/
  
