// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsc7wpHMP9oUIbpYgj-wtMC_V-194yN1Y',
    appId: '1:610143586884:web:53e5d8136279b225198a11',
    messagingSenderId: '610143586884',
    projectId: 'habit-tracker-7b489',
    authDomain: 'habit-tracker-7b489.firebaseapp.com',
    storageBucket: 'habit-tracker-7b489.firebasestorage.app',
    measurementId: 'G-9XHKD7S6BD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCpB6PKsakTPX5CaSo2yKl2e-NjdHNSOg8',
    appId: '1:610143586884:android:c7dec7539b735443198a11',
    messagingSenderId: '610143586884',
    projectId: 'habit-tracker-7b489',
    storageBucket: 'habit-tracker-7b489.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyABuaXgbCUuUUYzg8R4ITNPbsSWghelW18',
    appId: '1:610143586884:ios:0afdfbecec82c198198a11',
    messagingSenderId: '610143586884',
    projectId: 'habit-tracker-7b489',
    storageBucket: 'habit-tracker-7b489.firebasestorage.app',
    iosBundleId: 'com.example.habitTrackerApp',
  );
}
